# Generated by Django 2.0.6 on 2021-01-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('age', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pic', models.ImageField(null=True, upload_to='pic')),
            ],
            options={
                'db_table': 'stu',
            },
        ),
    ]
